// <auto-generated />
namespace DatabaseTW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class userInfo_fk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userInfo_fk));
        
        string IMigrationMetadata.Id
        {
            get { return "201505231639161_userInfo_fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
