// <auto-generated />
namespace DatabaseTW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class database4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(database4));
        
        string IMigrationMetadata.Id
        {
            get { return "201505230514038_database4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
